NAME = minishell

FILES = lexer_to_expender.c test_main.c 

SRC = $(addprefix src/, $(FILES))

SRCS = $(SRC) $(DEP)

OBJ = $(SRCS:.c=.o)

CFLAGS = -Wall -Wextra -Werror -Ilibft/ -Ienv/src/ -Iexpander/src/ $(FFLAGS)

FFLAGS = -fsanitize=address -g

RLINE = -lreadline

CC = cc

RM = rm -f


DETECTED_OS =	$(shell uname)


LIBFT_DIR =	./libft

LIBFT_SRC =	$(addprefix $(LIBFT_DIR)/, $(LIBFT_FILE))

LIBFT_FILE = 	ft_isascii.c ft_isalnum.c ft_isalpha.c ft_isdigit.c ft_isprint.c\
		ft_strlen.c ft_strlcpy.c ft_strlcat.c ft_strncmp.c ft_atoi.c\
		ft_strdup.c ft_strldup.c ft_tolower.c ft_toupper.c ft_strchr.c\
		ft_strrchr.c ft_strnstr.c ft_memset.c ft_bzero.c ft_memcpy.c\
		ft_memmove.c ft_memchr.c ft_memcmp.c ft_calloc.c ft_substr.c\
		ft_strjoin.c ft_strtrim.c ft_split.c ft_itoa.c ft_strmapi.c\
		ft_striteri.c ft_putchar_fd.c ft_putstr_fd.c ft_putendl_fd.c\
		ft_putnbr_fd.c ft_malloc.c ft_calloc_exit.c ft_strjoinf.c ft_strjoin_ff.c\
		ft_realloc_tab.c\


EXP_DIR = 	./expander

EXP_SRC = 	$(EXP_DIR)/src/cleaner.c $(EXP_DIR)/src/expander.c\


ENV_DIR = 	./env

ENV_SRC = 	$(addprefix $(ENV_DIR)/src/, $(ENV_FILE))

ENV_FILE =	ft_getenv.c env_list_manager.c env_to_list.c\
		env_reassign.c\


LEXER_DIR = 	./lexer

LEXER_FILE = 	lexer.c lexer_list_manager.c lexer_quotes.c lexer_quotes_utils.c\

LEXER_SRC = 	$(addprefix $(LEXER_DIR)/src/, $(LEXER_FILE))


PARSER_DIR = 	./parser

PARSER_FILE = 	simple_cmd.c

PARSER_SRC = 	$(addprefix $(PARSER_DIR)/src/, $(PARSER_FILE))



DEP = 		$(LIBFT_SRC) $(ENV_SRC) $(EXP_SRC) $(LEXER_SRC) $(PARSER_SRC)





$(NAME): $(OBJ)
		$(CC) $(CFLAGS) $(OBJ) -g $(RLINE) -g -o $(NAME)

.c.o:
		$(CC) $(CLFAGS) -c -g $< -g -o $(<:.c=.o)

###__RULES__###
all: $(NAME)

clean:
		$(RM) $(BIN)
		$(RM) $(OBJ)

fclean: clean
		$(RM) $(NAME)

re :	fclean $(NAME)


.PHONY: all clean fclean re 

# endif
